# Generated by Django 4.0 on 2021-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('gest', models.IntegerField()),
                ('arrival', models.DateField()),
                ('leaving', models.DateField()),
            ],
        ),
    ]
