# Generated by Django 4.0 on 2021-12-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
    ]
