# Generated by Django 4.0 on 2021-12-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_name_contact_name_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name_1',
            field=models.CharField(max_length=40),
        ),
    ]
