# Generated by Django 4.0 on 2021-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_contact_name_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email_1', models.EmailField(max_length=254)),
                ('number_1', models.IntegerField()),
                ('subject_1', models.CharField(max_length=10)),
                ('textarea_1', models.CharField(max_length=100)),
            ],
        ),
    ]
