# Generated by Django 4.0 on 2021-12-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='someone',
        ),
    ]
