# Generated by Django 4.0 on 2021-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_name_details_someone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
